n=float(input('Digite um número que eu mostro a tabuada... '))
v=0
int(v)
r=n*v
print('{} x {} = {}'.format(v,n,r))
v=v+1
r=n*v
print('{} x {} = {}'.format(v,n,r))
v=v+1
r=n*v
print('{} x {} = {}'.format(v,n,r))
v=v+1
r=n*v
print('{} x {} = {}'.format(v,n,r))
v=v+1
r=n*v
print('{} x {} = {}'.format(v,n,r))
v=v+1
r=n*v
print('{} x {} = {}'.format(v,n,r))
v=v+1
r=n*v
print('{} x {} = {}'.format(v,n,r))
v=v+1
r=n*v
print('{} x {} = {}'.format(v,n,r))
v=v+1
r=n*v
print('{} x {} = {}'.format(v,n,r))
v=v+1
r=n*v
print('{} x {} = {}'.format(v,n,r))
v=v+1
r=n*v
print('{} x {} = {}'.format(v,n,r))
v=v+1
